
import { SurfacePreset } from './types';

export const SURFACE_PRESETS: SurfacePreset[] = [
  {
    id: 'asphalt',
    name: 'Asphalt',
    data: `KEY=ROAD
FRICTION=0.98
DAMPING=0
WAV=
WAV_PITCH=0
FF_EFFECT=NULL
DIRT_ADDITIVE=0
BLACK_FLAG_TIME=0
IS_VALID_TRACK=1
SIN_HEIGHT=0
SIN_LENGTH=0
IS_PIT_LANE=0
VIBRATION_GAIN=0
VIBRATION_LENGTH=0`
  },
  {
    id: 'dirt',
    name: 'Dirt',
    data: `KEY=ROAD
_EXT_SURFACE_TYPE=DIRT
FRICTION=0.70
DAMPING=0
WAV=dirt.wav
WAV_PITCH=0
FF_EFFECT=NULL
DIRT_ADDITIVE=0.5
BLACK_FLAG_TIME=0
IS_VALID_TRACK=1
SIN_HEIGHT=0
SIN_LENGTH=0
IS_PIT_LANE=0
VIBRATION_GAIN=0.05
VIBRATION_LENGTH=0.1`
  },
  {
    id: 'ice',
    name: 'Ice',
    data: `KEY=ROAD
_EXT_SURFACE_TYPE=ICE
_EXT_SURFACE_TYPE_MODIFIER=REGULAR
FRICTION=0.15
DAMPING=0.01
WAV=
WAV_PITCH=0
FF_EFFECT=NULL
DIRT_ADDITIVE=0
BLACK_FLAG_TIME=0
IS_VALID_TRACK=1
SIN_HEIGHT=0
SIN_LENGTH=0
IS_PIT_LANE=0
VIBRATION_GAIN=0.02
VIBRATION_LENGTH=0.05`
  },
  {
    id: 'sand',
    name: 'Sand',
    data: `KEY=ROAD
_EXT_SURFACE_TYPE=SAND
_EXT_SURFACE_TYPE_MODIFIER=REGULAR
FRICTION=0.50
DAMPING=0.02
WAV=sand.wav
WAV_PITCH=0
FF_EFFECT=NULL
DIRT_ADDITIVE=0.7
BLACK_FLAG_TIME=0
IS_VALID_TRACK=1
SIN_HEIGHT=0
SIN_LENGTH=0
IS_PIT_LANE=0
VIBRATION_GAIN=0.1
VIBRATION_LENGTH=0.2`
  },
  {
    id: 'gravel',
    name: 'Gravel',
    data: `KEY=ROAD
_EXT_SURFACE_TYPE=GRAVEL
_EXT_SURFACE_TYPE_MODIFIER=REGULAR
GRAVEL_PRESET=2
FRICTION=0.65
DAMPING=0.02
WAV=gravel.wav
WAV_PITCH=0
FF_EFFECT=NULL
DIRT_ADDITIVE=0.7
BLACK_FLAG_TIME=0
IS_VALID_TRACK=1
SIN_HEIGHT=0
SIN_LENGTH=0
IS_PIT_LANE=0
VIBRATION_GAIN=0.15
VIBRATION_LENGTH=0.25`
  },
  {
    id: 'snow',
    name: 'Snow',
    data: `KEY=ROAD
_EXT_SURFACE_TYPE=SNOW
_EXT_SURFACE_TYPE_MODIFIER=REGULAR
FRICTION=0.35
DAMPING=0.02
WAV=snow.wav
WAV_PITCH=0
FF_EFFECT=NULL
DIRT_ADDITIVE=0.1
BLACK_FLAG_TIME=0
IS_VALID_TRACK=1
SIN_HEIGHT=0
SIN_LENGTH=0
IS_PIT_LANE=0
VIBRATION_GAIN=0.05
VIBRATION_LENGTH=0.1`
  }
];
